### PR TITLE
obtain go-xcat from xcat-extensions instead of xcat.org

### PR DESCRIPTION
**Pull request by immarvin**
see https://github.com/xcat2/xcat-core/issues/2290

### CODE REVIEW

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Comment by whowutwut** [comment]
@immarvin Is it better to just point to xcat-core? https://github.com/xcat2/xcat-core/blob/2.13/xCAT-server/share/xcat/tools/go-xcat

 If we point to go-xcat in xcat-extensions, then we have to delete the go-xcat from xcat-core.  It's not good to have copies in multiple places.

**Comment by neo954** [comment]
I prefer we just use the copy of `go-xcat` in the master branch of `xcat-core` repository. I believe spread the script `go-xcat` everywhere is not a good idea. For our convenience, let us reduce the copy of `go-xcat` we need to maintain manually.

**Comment by whowutwut** [comment]
yes, agreed.  I will make the changes today.

**Pull request merged**
