### PR TITLE
Add IRC link to the home page

### PR DESCRIPTION
**Pull request by arif-ali**

### CODE REVIEW

**Comment by whowutwut** [comment]
@arif-ali  is this IRC channel pretty active? :-)

**Comment by arif-ali** [comment]
We tend to have around 10 people normally logged in

We tend to get questions every so often, but if it gets advertised, maybe more people will join, and get a bit more activity

**Comment by whowutwut** [comment]
I actually have no isssue adding this to the xcat.org site. Worst case is that if everyone leaves the room, it will just be empty...   @zet809 , if no issues on your side, let's merge this.

**Comment by zet809** [comment]
Seems OK to me, it seems we won't get any message unless we log in the channel. @arif-ali Will you put an eye on it and if there is any question, you can forward it to us?

**Comment by arif-ali** [comment]
When there is anything, I or Jarrod do tend to respond. But if there is anything I cannot answer, I will feed it back here, or direct them here for any issues

**Pull request merged**
