### PR TITLE
Provide a cleanup script to remove the snapshot builds that are older than 180 days

### PR DESCRIPTION
**Pull request by whowutwut**
Fixes issue #22

This new script allows us to clean up the old files in the xcat.org server automatically.  Because we are building daily for certain releases, we do not want the file server to fill up on snapshot builds. 

In my test machine, `files/xcat/xcat-core` starts at 1.4G in size. 

Using a 180 day expiration, the resulting size is: 1.2 GB
Using a 30 day expiration, the resulting size is: 182 M

Here's the before and after listing of the directory using 30 days (`find ./ -name "*.bz2" -print`)
[before.txt](https://github.com/xcat2/xcat.org/files/683134/before.txt)
[after.txt](https://github.com/xcat2/xcat.org/files/683135/after.txt)

### CODE REVIEW

**Comment by whowutwut** [comment]
I actually think that maybe we should make this a 30 day clean up...

**Comment by whowutwut** [comment]
Do we think this is too risky to merge? Even after we mege, we would need to activate it into the cron table to have it running....

**Comment by whowutwut** [comment]
@daniceexi @zet809  Is this something we should consider as xcat.org will continue to grow in size..

**Comment by daniceexi** [comment]
@whowutwut I think it should be ok to merge your change that remove the 30days old build. Generally the snapshot build is not useful when it older than one month.  Even we need it someday later, there's still one copy in our gpfs storage.

**Comment by whowutwut** [comment]
I'm going to merge this in.  We don't need to activate if we do not create a cron job.

**Pull request merged**
