### PR TITLE
Changes for the 2.13 release

### PR DESCRIPTION
**Pull request by whowutwut**
Update the xcat.org pages in preparation for the 2.13 release

### CODE REVIEW

**Comment by whowutwut** [comment]
If OK, feel free to merge. . The changes are not reflected on xcat.org until we merge this into stable and then pull the changes on xcat.org.

**Comment by tingtli** [comment]
@whowutwut  there is some lines about the online repo ( Line 70, 83, 86,106,116,119 )
I think we need to point to 2.13.

**Comment by whowutwut** [comment]
:+1:  Thanks @tingtli !  I update the pull request.  I will need to verify that the promote script does in fact work on the major release and creates the "latest" repo correctly.  I still do not know a good way to have a staging area where we can validate these changes ahead of time.

**Comment by whowutwut** [comment]
I will merge this to start some verification.

**Pull request merged**
