### PR TITLE
Change xcat.org files in preparation for the 2.12.1 release

### PR DESCRIPTION
**Pull request by whowutwut**
Modify the index.html and download.html files to update the links
Address issue #15 

you can view the staging files here: http://xcat.org/staging/whowutwut/

### CODE REVIEW

**Comment by whowutwut** [comment]
Before merging this pull request... how do we plan to manage this xcat.org repo? 

Currently the xcat.org server is on the "master" branch. Should this be changed to 2.12? 
1. Then we merge this pull request against the master branch...
2. On the 2.12.1 GA, we can merge master -> 2.12 branch 
3. On xcat.org, we do a `git checkout 2.12; git pull 2.12` ?

**Comment by daniceexi** [comment]
My idea is we don't have to make xcat.org align with the xCAT release. We just need to maintain two branches: stable and devel (mater branch). 

- xcat.org always points to the stable branch;
- xcat.org/devel points to the master branch;
- We test the new download page for next release in the master branch; that means the test page can be saw in the xcat.org/devel;
- When the commits in the master has been tested. Just before the GA, we merge all the commits from master to stable branch. And then 'git pull' from the xcat.org to make it online.

**Comment by whowutwut** [comment]
@daniceexi  Thanks for the input.  I think that's a good idea. 

I did the following today:
- created a branch "stable" off of the master  and switched xcat.org to be using "stable"
- under xcat.org, renamed the `staging.vhu` to `staging` and renamed my clone to `whowutwut`. This way others can also test changes under the staging directory.   Updated the link above: http://xcat.org/staging/whowutwut/
- deleted the 2.11 branch 

If you are OK with the pull request, we can merge it into master, then merge master to stable like you suggested when we get closer to GA.  Or leave it open to fix any issues that might come up when testing off the URL above.

**Comment by daniceexi** [comment]
The change looks good to merge.

**Comment by daniceexi** [comment]
@whowutwut I removed your personal repo ``/var/www/xcat.org/staging/whowutwut`` and make the ``/var/www/xcat.org/staging/`` to be the default testing repo. Now we can test the pre-GA pages through URL http://xcat.org/staging/

**Comment by whowutwut** [comment]
@daniceexi  Ok.  That is fine. 

The one thing I don't like about this is that the staging directory is cloned directly against the xcat2/xcat.org project...  Where the one that I had was cloned against my forked copy.  This allowed me to have a place to test out my changes on the xcat.org server and symlink the files directory to my forked copy.. test my changes and create a pull request.  

What you did will just allow us to test the already merged changes.  I don't think we should push directly to xcat2/xcat.org...

**Comment by daniceexi** [comment]
@whowutwut 
* I'd like the staging directory to be for xcat.org online test only. We could find another dir for the personal test purpose.
* how about use local xcat MN to run the test as what we are using local MN to test the xCAT doc change?

**Comment by whowutwut** [comment]
Yea, another directory would work.  If we do not need access to the files directory, it will be okay.  It's only if we need to test some changes to the files directory that it would be easier to symlink the files.  We could also use the xcat.org backup files to do testing as well.

**Comment by whowutwut** [comment]
@daniceexi with Pull request #22 , the `backup/cleanup_files.sh` is in the master branch.  How do we get this change into the stable branch and updated on xcat.org.

**Comment by daniceexi** [comment]
@whowutwut 
I did it this way:

Find a server to merge commits from master branch to stable branch
~~~~
git clone https://github.com/xcat2/xcat.org.git xcat.org
cd xcat.org
git branch stable origin/stable
git checkout stable
git merge master
git push origin stable
~~~~

Pull the latest change on xcat.org
~~~~
cd <xcat.org www root dir>
git pull
~~~~

**Comment by whowutwut** [comment]
Thanks, so this means that we need to merge `master -> stable` and go a `git pull` before we are able to see the new changes.

**Comment by daniceexi** [comment]
yes, you are right.

**Pull request merged**
